//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Apple.java
//  @ Date : 2012/11/5
//  @ Author : 
//
//

package org.redtroy.study.pattern.factory.simple;

public class Apple implements org.redtroy.study.pattern.factory.simple.Fruit {
	public void grow() {
	}

	public void harvest() {
	}
}
