//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FruitFactory.java
//  @ Date : 2012/11/5
//  @ Author : 
//
//

package org.redtroy.study.pattern.factory.simple;

public class FruitFactory {
	public static Fruit produce(String fruitName) {
		System.out.println(fruitName);
		return null;
	}
}
