//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Fruit.java
//  @ Date : 2012/11/5
//  @ Author : 
//
//



package org.redtroy.study.pattern.factory.simple;


public interface Fruit {
	public void grow();
	public void harvest();
}
