//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AbstractFactory.java
//  @ Date : 2012/11/5
//  @ Author : 
//
//

package org.redtroy.study.pattern.factory.method;

public abstract class AbstractFactory {
	public static AbstractProduct produce() {
		return null;
	}
}
