//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ConcreteProduct.java
//  @ Date : 2012/11/5
//  @ Author : 
//
//

package org.redtroy.study.pattern.factory.method;

public class ConcreteProduct implements AbstractProduct {
}
