//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ConcreteFactory.java
//  @ Date : 2012/11/5
//  @ Author : 
//
//

package org.redtroy.study.pattern.factory.method;

public class ConcreteFactory extends AbstractFactory {
}
