select * from hrdepartment

select PDEPTID PDEPTID,DEPTID DEPTID,DEPTTEL DEPTTEL,QQ QQ,CHIEF_MOBILE CHIEF_MOBILE,CHIEF_NAME CHIEF_NAME,DEPTNAME DEPTNAME,CHIEF_FAX CHIEF_FAX,ORGID ORGID from HRDEPARTMENT where PDEPTID = 1 and DEPTID = 19
