CREATE TABLE DRMROWPRIVIL (
	ROLEID VARCHAR(64) NOT NULL,
	TABLENAME VARCHAR(255) NOT NULL,
	SUBWHERE VARCHAR(255),
	PRIMARY KEY (TABLENAME,ROLEID)
);

CREATE TABLE DRMROLE (
	ROLEID VARCHAR(64) NOT NULL,
	ROLENAME VARCHAR(128),
	STATUS INT,
	ROLELEVEL SMALLINT,
	PRIMARY KEY (ROLEID)
);

CREATE TABLE DRMSUBJECTDIM (
	SCODE VARCHAR(12) NOT NULL,
	DCODE VARCHAR(12) NOT NULL,
	NAME VARCHAR(60),
	FIELDCODE VARCHAR(60),
	VALUETYPE VARCHAR(12),
	PRIMARY KEY (SCODE,DCODE)
);

CREATE TABLE DRMSUBJECTCOND (
	SCODE VARCHAR(12) NOT NULL,
	CCODE VARCHAR(12) NOT NULL,
	NAME VARCHAR(60),
	FIELDCODE VARCHAR(60),
	VALUETYPE VARCHAR(12),
	PRIMARY KEY (SCODE,CCODE)
);

CREATE TABLE BUGMENU (
	MENUNAME VARCHAR(30) NOT NULL,
	MENULABEL VARCHAR(20),
	PARENTMENUNAME VARCHAR(30),
	FUNCNO VARCHAR(128),
	MENULEVEL INT,
	DISPORDER INT,
	PRIMARY KEY (MENUNAME)
);

CREATE TABLE DRMBIZDATADICT (
	TABLENAME VARCHAR(128) NOT NULL,
	COLNAME VARCHAR(128) NOT NULL,
	COLCODE VARCHAR(64) NOT NULL,
	COLVALUE VARCHAR(128),
	PRIMARY KEY (COLNAME,COLCODE,TABLENAME)
);


CREATE TABLE HRPOSTROLE (
	POSTID INT DEFAULT 0 NOT NULL,
	ROLEID VARCHAR(32) NOT NULL,
	PRIMARY KEY (ROLEID,POSTID)
);


CREATE TABLE DRMUSERROLE (
	USERID VARCHAR(32) NOT NULL,
	ROLEID VARCHAR(32) NOT NULL,
	STATUS INT,
	REFCOUNT INT DEFAULT 1,
	PRIMARY KEY (USERID,ROLEID)
);

CREATE TABLE DRMTABLE (
	TABLENAME VARCHAR(128) NOT NULL,
	DISPLAYNAME VARCHAR(128) DEFAULT 'Y',
	MEMO VARCHAR(512),
	RESERVED1 VARCHAR(64),
	RESERVED2 VARCHAR(64),
	RESERVED3 VARCHAR(64),
	RESERVED4 VARCHAR(64),
	RESERVED5 VARCHAR(64),
	PRIMARY KEY (TABLENAME)
);

CREATE TABLE DRMMENU (
	MENUNAME VARCHAR(30) NOT NULL,
	MENULABEL VARCHAR(20),
	PARENTMENUNAME VARCHAR(30),
	FUNCNO VARCHAR(128),
	MENULEVEL INT,
	DISPORDER INT,
	PRIMARY KEY (MENUNAME)
);

CREATE TABLE DRMERROR (
	ERRCODE INT DEFAULT 0 NOT NULL,
	ERRLEVEL INT,
	ERRMESSAGE VARCHAR(512),
	PRIMARY KEY (ERRCODE)
);

CREATE TABLE DRMSUBJECT (
	SCODE VARCHAR(12) NOT NULL,
	NAME VARCHAR(60),
	TITLE VARCHAR(120),
	GROUPNAME VARCHAR(12),
	FIELDCODE VARCHAR(60),
	FROMTABLES VARCHAR(60),
	TABLEJOINS VARCHAR(120),
	DAONAME VARCHAR(60),
	PRIMARY KEY (SCODE)
);

CREATE TABLE DRMCOLPRIVIL (
	ROLEID VARCHAR(30) NOT NULL,
	TABLENAME VARCHAR(128) NOT NULL,
	COLNAME VARCHAR(128) NOT NULL,
	PRIVIL VARCHAR(2),
	PRIMARY KEY (ROLEID,COLNAME,TABLENAME)
);

CREATE TABLE HRORGROLE (
	ORGID INT DEFAULT 0 NOT NULL,
	ROLEID VARCHAR(32) NOT NULL,
	PRIMARY KEY (ROLEID,ORGID)
);

CREATE TABLE DRMCOLUMN (
	TABLENAME VARCHAR(128) NOT NULL,
	COLNAME VARCHAR(128) NOT NULL,
	COLTYPE VARCHAR(12),
	COLLEN INT DEFAULT 0,
	COLPRECISION SMALLINT,
	ISNULLABLE CHAR(1) DEFAULT 'Y',
	ISPK CHAR(1) DEFAULT 'N',
	REFTABNAME VARCHAR(128),
	REFCOLNAME VARCHAR(128),
	DISPLAYNAME VARCHAR(128),
	DISPLAYTYPE CHAR(1),
	DISPLAYSEQ INT,
	DATASOURCE VARCHAR(6),
	FORMAT VARCHAR(32),
	CANSEARCH CHAR(1) DEFAULT 'N',
	RESVERED1 VARCHAR(32),
	RESVERED2 VARCHAR(32),
	RESVERED3 VARCHAR(32),
	RESVERED4 VARCHAR(32),
	RESVERED5 VARCHAR(32),
	PRIMARY KEY (TABLENAME,COLNAME)
);

CREATE TABLE DRMROLEMENU (
	ROLEID VARCHAR(32) NOT NULL,
	MENUNAME VARCHAR(30) NOT NULL,
	PRIMARY KEY (ROLEID,MENUNAME)
);

CREATE TABLE DRMFILEUPLOADLOG (
	FILEID INT DEFAULT 0 NOT NULL,
	NAME VARCHAR(512),
	EXTNAME VARCHAR(64),
	SIZE INT,
	FILEURL VARCHAR(512),
	UPLOADTIME DATETIME,
	RELOADTIMIE DATETIME,
	GROUPTYPE VARCHAR(20),
	GROUPNO VARCHAR(40),
	PRIMARY KEY (FILEID)
);

CREATE TABLE HREMPPOST (
	EMPID INT DEFAULT 0 NOT NULL,
	POSTID INT DEFAULT 0 NOT NULL,
	FROMDATE DATETIME,
	TODATE DATETIME,
	PRIMARY KEY (POSTID,EMPID)
);


CREATE TABLE DRMROLEFUNCTION (
	FUNCNO VARCHAR(128) NOT NULL,
	ROLEID VARCHAR(32) NOT NULL,
	PRIMARY KEY (ROLEID,FUNCNO)
);

CREATE TABLE DRMFUNCTION (
	FUNCNO VARCHAR(128) NOT NULL,
	FUNCNAME VARCHAR(128),
	FUNCSTATUS SMALLINT,
	FUNCPARAMS VARCHAR(128),
	PRIMARY KEY (FUNCNO)
);

CREATE TABLE HREMPLOYEE (
	EMPID INT DEFAULT 0 NOT NULL,
	ORGID INT,
	NAME VARCHAR(60),
	EMAIL VARCHAR(120),
	TEL VARCHAR(12),
	ADDRESS VARCHAR(80),
	ZIPCODE VARCHAR(12),
	STATUS INT DEFAULT 1,
	GENDER CHAR(1) DEFAULT 'F',
	BIRTHDATE DATETIME,
	REGDATE TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL,
	MOBILETEL VARCHAR(12),
	EMPLEVEL DOUBLE DEFAULT 1,
	MARRIAGE CHAR(1) DEFAULT 'N',
	EMPTYPE CHAR(1) DEFAULT 'F',
	TELH VARCHAR(12),
	DEGREE CHAR(1) DEFAULT 'B',
	LASTSCHOOL VARCHAR(60),
	EMCONTACT VARCHAR(60),
	EMCONTACTTEL VARCHAR(12),
	PRIMARY KEY (EMPID)
);

CREATE TABLE DRMUSER (
	USERID VARCHAR(32) NOT NULL,
	USERPASSWORD VARCHAR(64),
	USERSTATUS INT DEFAULT 1,
	USERSTATUSTIME DATE ,
	USERIP VARCHAR(50),
	USERSTARTIP VARCHAR(50),
	USERENDIP VARCHAR(50),
	USERLOGINONLYTHISIP SMALLINT DEFAULT 0,
	USERFAILURELOGINCOUNT INT DEFAULT 0,
	USERLASTLOGINTIME DATE,
	USERTYPE CHAR(1),
	USERNO INT,
	ISONLINE INT DEFAULT 0,
	PRIMARY KEY (USERID)
);

CREATE TABLE HRPOST (
	POSTID INT DEFAULT 0 NOT NULL,
	ORGID INT,
	POSTNO VARCHAR(80),
	NAME VARCHAR(80),
	ISMANAGER CHAR(1) DEFAULT 'N',
	PARENT_POSTID INT,
	POSTSEQ VARCHAR(100),
	ISLEADER CHAR(1) DEFAULT 'N',
	PRIMARY KEY (POSTID)
);

CREATE TABLE HRORGANIZATION (
	ORGID INT DEFAULT 0 NOT NULL,
	ORGNO VARCHAR(12),
	TYPE CHAR(1),
	NAME VARCHAR(40),
	EMAIL VARCHAR(120),
	TEL VARCHAR(120),
	WEB VARCHAR(256),
	PARENT_ORGID INT DEFAULT 0,
	ORGSEQ VARCHAR(80),
	PRIMARY KEY (ORGID)
);

CREATE INDEX DRMROLEFUNCTION_FK ON DRMROLEFUNCTION (FUNCNO ASC);

CREATE INDEX SUBJECTCONDITION_FK ON DRMSUBJECTCOND (SCODE ASC);

CREATE INDEX DRMROLEFUNCTION_FK2 ON DRMROLEFUNCTION (ROLEID ASC);

CREATE UNIQUE INDEX AK_IX_DRMUSER_USERTYP_DRMUSER ON DRMUSER (USERNO ASC);

CREATE INDEX DRMROLEMENU_FK ON DRMROLEMENU (ROLEID ASC);

CREATE INDEX FUNCMENU_FK ON DRMMENU (FUNCNO ASC);

CREATE INDEX DRMROLEMENU_FK2 ON DRMROLEMENU (MENUNAME ASC);

CREATE INDEX FK_POST_REF_DEPT_FK ON HRPOST (ORGID ASC);

CREATE INDEX FK_DRMCOLUMN_DRMTABLE_FK ON DRMCOLUMN (TABLENAME ASC);

CREATE INDEX FK_EMPPOST_REF_POST_FK ON HREMPPOST (POSTID ASC);

CREATE INDEX FK_EMP_REF_DEPT_FK ON HREMPLOYEE (ORGID ASC);

CREATE INDEX SUBJECTDIMENSION_FK ON DRMSUBJECTDIM (SCODE ASC);

CREATE INDEX FK_EMPPOST_REF_EMP_FK ON HREMPPOST (EMPID ASC);

CREATE INDEX FK_DRMUSERROLES_DRMROLE_FK ON DRMUSERROLE (ROLEID ASC);

CREATE INDEX FK_DRMUSERROLES_DRMUSER_FK ON DRMUSERROLE (USERID ASC);

CREATE UNIQUE INDEX AK_IX_DRMUSER_USERTYP_DRMUSER ON DRMUSER (USERTYPE ASC);

CREATE INDEX FK_ORGROLE_REF_ORG_FK ON HRORGROLE (ORGID ASC);

CREATE INDEX FK_POSTROLE_REF_POST_FK ON HRPOSTROLE (POSTID ASC);

