/**
 *all rights reserved,@copyright 2003
 */
package com.cots.gui;

import javax.swing.*;

/**
 * Description:
 * <p/>
 * User: chuguanghua
 * Date: 2005-1-26
 * Time: 9:34:09
 * Version: 1.0
 */
public class ActionEditor {
    private JPanel contentPanel;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// !!! IMPORTANT !!!
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * !!! IMPORTANT !!!
     * DO NOT edit this method OR call it in your code!
     */
    private void $$$setupUI$$$() {
        contentPanel = new JPanel();
        contentPanel.setBorder(BorderFactory.createTitledBorder("Action Editor"));
    }
}
