//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : EagerSingleton.java
//  @ Date : 2012/11/14
//  @ Author : 
//
//

package org.redtroy.study.pattern.singleton;

public class EagerSingleton {
	public static EagerSingleton instance = new EagerSingleton();

	private EagerSingleton() {

	}

	public static EagerSingleton newInstance() {
		return instance;
	}
}
